### ISSUE TITLE
Error EXCEPTION_ACCESS_VIOLATION 

### ISSUE THREAD

**Issue by hardwayy** [ishin4762/ue4-realtime-delay#1] opened 2024-07-04 12:56 UTC
I get a EXCEPTION_ACCESS_VIOLATION crash everytime I start my game, with the first line of code prompting to the plugin's folder.

**Comment by hardwayy** [comment] 2024-07-04 12:58
> I get a EXCEPTION_ACCESS_VIOLATION crash everytime I start my game, with the first line of code prompting to the plugin's folder.
![Screenshot 2024-07-04 145814](https://github.com/ishin4762/ue4-realtime-delay/assets/152190076/03b7cbc8-3ad9-4755-8607-cf21ad5fa019)

**Comment by ishin4762** [comment] 2024-07-04 18:36
@hardwayy Thank you for contacting!
Which version of the Unreal Engine is causing the problem?

**Comment by hardwayy** [comment] 2024-07-04 22:59
> @hardwayy Thank you for contacting! Which version of the Unreal Engine is causing the problem?

Hello, it's 5.4

**Comment by ishin4762** [comment] 2024-07-06 14:40
> > @hardwayy Thank you for contacting! Which version of the Unreal Engine is causing the problem?
> 
> Hello, it's 5.4

Thank you very much.

I would like to receive additional information as I cannot reproduce the crash...
From which class and from which event did you run the Realtime Delay node?

**Comment by hardwayy** [comment] 2024-07-06 16:47
I have a simple cursor on a 90 degree slide that goes up and down to aim in my prototype of a 2d runner.

https://github.com/ishin4762/ue4-realtime-delay/assets/152190076/fb6ca762-8141-4a9b-972e-cf716eeb7b7d
The movement of the cursor isn't actually done in the widget animation, I have a Blueprint Actor that calls both the slide and the cursor separately, and uses and arrow to move the cursor alongside the slide, since I can determine the direction of the cursor from there.
I can't actually display the real method in action since it would crash as usual lol.

The realtime delay isn't used for that: when the player escapes just barely from an obstacle, it switches to a close-up camera and sets the global time dilation to 0.1- I use the realtime delay node to wait 2 seconds in real time and switch back to the normal camera and set the time dilation back to the normal one.
![immagine](https://github.com/ishin4762/ue4-realtime-delay/assets/152190076/6852bdd4-8624-43f9-aa4a-48cd8faa3ee0)
It's called from the player blueprint, which is an actor class.
Thanks for replying by the way :)

**Comment by ishin4762** [comment] 2024-07-10 19:08
@hardwayy 
I'm not sure if it is directly related to this issue, but I found a bug that causes a crash when an object is destroyed while running Realtime Delay, and I have fixed it in the following pull request.
#2 

Please download the latest main branch and see if the problem is fixed.

**Comment by hardwayy** [comment] 2024-07-12 12:51
> @hardwayy I'm not sure if it is directly related to this issue, but I found a bug that causes a crash when an object is destroyed while running Realtime Delay, and I have fixed it in the following pull request. #2
> 
> Please download the latest main branch and see if the problem is fixed.

Hello, sorry for the late reply: I installed the new version but it keeps crashing with the same error, linking to the RealtimeDelayAction.cpp at line 50.

**Comment by hardwayy** [comment] 2024-07-12 12:54
Here's the full log if you need it:
Fatal error!

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x00000556888bfdf4

0x00007ffebda37469 UnrealEditor-CoreUObject.dll!UnknownFunction []
0x00007ffebdd46129 UnrealEditor-CoreUObject.dll!UnknownFunction []
0x000002e54bfa3e31 UnrealEditor-RealtimeDelay.dll!URealtimeDelayActionManager::Tick() [C:\Users\david\Documents\Unreal Projects\brunner\Plugins\RealtimeDelay\Source\RealtimeDelay\Private\RealtimeDelayAction.cpp:50]
0x00007ffe6ed701b5 UnrealEditor-Engine.dll!UnknownFunction []
0x00007ffeba725bb7 UnrealEditor-UnrealEd.dll!UnknownFunction []
0x00007ffebb37ea06 UnrealEditor-UnrealEd.dll!UnknownFunction []
0x00007ff67fa98af2 UnrealEditor.exe!UnknownFunction []
0x00007ff67fabd28c UnrealEditor.exe!UnknownFunction []
0x00007ff67fabd37a UnrealEditor.exe!UnknownFunction []
0x00007ff67fac0854 UnrealEditor.exe!UnknownFunction []
0x00007ff67fad6984 UnrealEditor.exe!UnknownFunction []
0x00007ff67fad9d7a UnrealEditor.exe!UnknownFunction []
0x00007fff3909257d KERNEL32.DLL!UnknownFunction []

**Comment by hardwayy** [comment] 2024-07-12 14:19
After some more tests, I can confirm the update fixewd my issue. Thank you!

**Comment by ishin4762** [comment] 2024-07-13 05:37
@hardwayy 
Thank you for confirming. I am glad to hear that the problem has been resolved!
Perhaps the plugin has been recompiled and the fix has been reflected.
I would be happy to hear from you if you need further assistance.

This issue has been resolved and will be closed.

**Closed as completed** 2024-07-13 05:37 UTC
Labels: bug
